EPIC SHIPS DATA + new Epic Hardpoints + Squid
guidokessels/xwing-data2 pull request #483
Opened 2021-11-02 21:08 UTC by Apollonaut13

I'm completely in the dark about the "ffg" numbers in the data, these will need to be fixed before this is pushed. Everything else should be accurate.

2021-11-02 21:10 UTC, Apollonaut13 commented
I'm also not certain about the placement of the "Attack" data being in the "Offline" section of the Hardpoints, but that's what was there before and I was just matching what I saw.

2021-11-05 07:18 UTC, danrs approved these changes

2021-11-05 07:18 UTC, danrs commented on data/upgrades/hardpoint.json
> +        "artwork": "https://squadbuilder.fantasyflightgames.com/card_art/190fb055e605840f31474e7c0d908f3a.jpg"
tbh you can just bin these fields, they are obsolete, but whatever

2021-11-05 07:19 UTC, danrs requested changes
Code is all fine - but we need to fix the tests so that they can understand epic ships. It's failing because epic ships don't match the ship schema expected in the tests

2021-11-05 07:42 UTC, danrs approved these changes

2021-11-05 07:56 UTC, merged